import { Task } from "../types/task";

export const mockTasks: Task[] = [
  {
    id: 1,
    user_id: "user-1",
    title: "Complete project documentation",
    description: "Write comprehensive documentation for the todo app project",
    completed: false,
    priority: "high",
    tags: ["work", "documentation"],
    due_date: "2025-01-30",
    reminder_time: null,
    recurring_pattern: null,
    next_occurrence: null,
    original_task_id: null,
    created_at: "2025-01-27T10:00:00Z",
    updated_at: "2025-01-27T10:00:00Z",
  },
  {
    id: 2,
    user_id: "user-1",
    title: "Review code changes",
    description: "Review pull requests and provide feedback",
    completed: true,
    priority: "medium",
    tags: ["work", "code-review"],
    due_date: "2025-01-28",
    reminder_time: null,
    recurring_pattern: null,
    next_occurrence: null,
    original_task_id: null,
    created_at: "2025-01-26T14:00:00Z",
    updated_at: "2025-01-27T09:00:00Z",
  },
  {
    id: 3,
    user_id: "user-1",
    title: "Buy groceries",
    description: "Milk, eggs, bread, vegetables",
    completed: false,
    priority: "low",
    tags: ["personal", "shopping"],
    due_date: null,
    reminder_time: null,
    recurring_pattern: null,
    next_occurrence: null,
    original_task_id: null,
    created_at: "2025-01-27T08:00:00Z",
    updated_at: "2025-01-27T08:00:00Z",
  },
  {
    id: 4,
    user_id: "user-1",
    title: "Team meeting",
    description: "Weekly standup meeting with the development team",
    completed: false,
    priority: "medium",
    tags: ["work", "meeting"],
    due_date: "2025-01-29",
    reminder_time: null,
    recurring_pattern: "weekly",
    next_occurrence: "2025-02-05",
    original_task_id: null,
    created_at: "2025-01-20T10:00:00Z",
    updated_at: "2025-01-20T10:00:00Z",
  },
];

