apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  labels:
    app.kubernetes.io/name: todo-chatbot
    app.kubernetes.io/component: backend
data:
  DATABASE_URL: {{ .Values.secret.databaseUrl | b64enc | quote }}
  BETTER_AUTH_SECRET: {{ .Values.secret.betterAuthSecret | b64enc | quote }}
  OPENROUTER_API_KEY: {{ .Values.secret.openrouterApiKey | b64enc | quote }}
